ils/ils/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf import settings
# from incidents_nsir.forms import CustomPasswordResetForm
admin.autodiscover()

urlpatterns = patterns('',
    # url('^', include('django.contrib.auth.urls')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy(settings.DEFAULT_TAXONOMY + ":report")),name="home"),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^password_reset/$', 'incidents_nsir.reset_views.password_reset', name="password_reset"),
    # url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
    # url(r'^logout$', 'django.contrib.auth.views.logout',{'next_page':reverse_lazy("login")}, name="logout"),
    url(r'^nsir/', include('incidents_nsir.urls', namespace="incidents_nsir", app_name="incidents_nsir")),
    url(r'^notifications_nsir/', include('notifications_nsir.urls', namespace="notifications_nsir", app_name="notifications_nsir")),
    url(r'^comments/', include('fluent_comments.urls')),

    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout',{'next_page':reverse_lazy("login")}, name="logout"),
    url(r'^password_change/$', 'incidents_nsir.reset_views.password_change', name='password_change'),
    url(r'^password_change/done/$', 'incidents_nsir.reset_views.password_change_done', name='password_change_done'),
    url(r'^password_reset/$', 'incidents_nsir.reset_views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'incidents_nsir.reset_views.password_reset_done', name='password_reset_done'),
    # Support old style base36 password reset links; remove in Django 1.7
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'incidents_nsir.reset_views.password_reset_confirm_uidb36'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'incidents_nsir.reset_views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'incidents_nsir.reset_views.password_reset_complete', name='password_reset_complete'),
    # The following urlconf allows access to media files (images uploaded to incidents)
    url(r'^media/incidentimages/(?P<filename>.*)$', 'incidents_nsir.views.protected_media')
)

# This method only works for serving media files on dev server. The production server
# can serve as well, but need to restrict access to files (only if logged in)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ils/notifications_nsir/urls.py
from django.conf.urls import patterns, include, url
import views

# Table of contents for views provided in views.py (for notifications app)
urlpatterns = patterns('',
    url(r'^unsubscribe/(?P<incident_id>\d+)/$', views.Unsubscribe.as_view(), name="unsubscribe"),
    url(r'^subscribe/(?P<incident_id>\d+)/$', views.Subscribe.as_view(), name="subscribe"),
)

ils/notifications_nsir/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

# Subscription model. One user can have multiple subscriptions (i.e. one or zero subscriptions
# to each Incident in the database)
class Subscription(models.Model):
    """Model to represent a subscription of a particular ILSUser to a particular incident.

    Subscriptions between an ILSUser and an Incident are used when sending email
    notifications. An ILSUser may be subscribed to many Incidents, and an Incident may
    be subscribed by many ILSUsers.
    """
    user = models.ForeignKey(User)
    incident = models.ForeignKey('incidents_nsir.Incident', related_name="subscription", null=True, blank=True)

    def __unicode__(self):
        return "Subscription (%s, %s)" % (self.user.get_name(), self.incident.incident_id)

class ReminderType(models.Model):
    """Model to represent a reminder, that contains information on the frequency with
    which reminders should be sent to investigators of incomplete investigations.
    """

    name = models.CharField(max_length=255, null=True, blank=True,
        help_text="verbose name of the reminder type"
    )
    reminder_type = models.CharField(max_length=255, null=True, blank=True,
        help_text="code name of the reminder type- should not change"
    )
    frequency_days = models.PositiveIntegerField(null=True, blank=True,
        help_text="number of days that define the frequency of this reminder"
    )

    def __unicode__(self):
        return self.name

ils/notifications_nsir/views.py
from django.contrib import messages
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.views.generic import DeleteView, View

from . import models
from incidents_nsir.models import Incident
from incidents_nsir.views import LoginRequiredMixin

#*****************************************************************************************
# These views can be accessed directly using the URLconfs defined in urls.py, or more
# commonly, using the Subscribe/Unsubscribe links provided on each Incident page.
#*****************************************************************************************

class Subscribe(View):
    """View used to subscribe the current user to a particular incident.
    """
    template_name_suffix = "_create"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        """Create the Subscription object and webpage for particular incident.

        Redirect the user to the investigation page to which they are subscribing, and
        display a message indicating that they have subscribed successfully or that they
        were already subscribed.
        """
        incident_id = self.kwargs['incident_id']
        my_inc = Incident.objects.get(incident_id=incident_id)
        inc_pk = my_inc.pk
        print inc_pk
        print self.request.user
        sub_instance, was_created = models.Subscription.objects.get_or_create(user=self.request.user, incident=my_inc)
        if was_created:
            messages.success(request, "You are now subscribed to Incident %s" % incident_id)
        else:
            messages.warning(request, "You are already subscribed to Incident %s" % incident_id)

        # Redirect user to the URL of the incident they subscribed to.
        return HttpResponseRedirect(reverse("incidents_nsir:incident", kwargs={"incident_id":incident_id}))


class Unsubscribe(LoginRequiredMixin, DeleteView):
    """View used to subscribe the current user from a particular incident.
    """
    model = models.Subscription

    def get(self, request, *args, **kwargs):
        """Delete the Subscription object and webpage for particular incident.

        Redirect the user to the investigation page to which they are subscribing, and
        display a message indicating that they have unsubscribed successfully or that they
        were not previously subscribed.
        """
        # if self.request.user.is_anonymous():
        #     return HttpResponseRedirect(reverse("login"))

        try:
            return super(Unsubscribe, self).get(self,request)
        except ObjectDoesNotExist: # I.e. no subscription matching this
            print self.kwargs["incident_id"]
            try:
                Incident.objects.get(incident_id=self.kwargs["incident_id"])
                return render(request, "notifications_nsir/no_subscription.html", {'incident_id': self.kwargs["incident_id"], 'exists': True})
            except ObjectDoesNotExist:
                return render(request, "notifications_nsir/no_subscription.html", {'incident_id': self.kwargs["incident_id"], 'exists': False})

    def get_object(self, *args, **kwargs):
        """Get the subscription object associated with a given ILSUser and Incident.
        """
        incident_id = self.kwargs["incident_id"]
        my_inc = Incident.objects.get(incident_id=incident_id)
        inc_pk = my_inc.pk
        obj = models.Subscription.objects.get(user=self.request.user, incident=inc_pk)
        return obj

    def get_success_url(self):
        """Define the URL to be accessed upon successful unsubscription.
        """
        if "cancel" not in self.request.POST:
            messages.success(self.request, "Successfully unsubscribed from Incident #%d" % (self.object.incident.incident_id))

        if self.request.POST.get("next", None) == "incident":
            return reverse("incidents_nsir:incident", kwargs={"incident_id":self.kwargs['incident_id']})
        elif self.request.user.is_investigator:
            return reverse("incidents_nsir:dashboard")

        return reverse("incidents_nsir:report")

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            return HttpResponseRedirect(self.get_success_url())

        return super(Unsubscribe, self).post(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(Unsubscribe, self).get_context_data(*args, **kwargs)
        context["next"] = self.request.GET.get("next", None)
        return context

ils/notifications_nsir/templates/notifications_nsir/no_subscription.html
{% extends BASE_TEMPLATE %}

{% block title %}No Subscription found{% endblock title %}

{% block page_title %}<h3>No Subscription found</h3>{% endblock page_title %}

{% block extra_css %}
{% endblock extra_css %}

{% block extra_js %}
{% endblock %}

{% block content %}

<div class="row">
    <div class="span5">
        {#<form action="" method="post">{% csrf_token %}#}
        {% if exists %}
            <p>You are not currently subscribed to Incident #{{incident_id}}</p>
            <a href="{% url 'notifications_nsir:subscribe' incident_id=incident_id %}?next=incident" title="Subscribe to this incident"> Click here to Subscribe</a>
        {% else %}
            <p>There is no incident with ID #{{incident_id}}</p>
        {% endif%}
        {#</form>#}
    </div>
</div>

{% endblock content %}

ils/notifications_nsir/templates/notifications_nsir/subscription_confirm_delete.html
{% extends BASE_TEMPLATE %}

{% block title %}Unsubscribe{% endblock title %}

{% block page_title %}<h3>Unsubscribe</h3>{% endblock page_title %}

{% block extra_css %}
{% endblock extra_css %}

{% block extra_js %}
{% endblock %}

{% block content %}

<div class="row">
    <div class="span5">
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to unsubscribe from Incident #{{object.incident.incident_id}}?</p>
            <span class="pull-right">
                {% if next == "incident" %}
                <input type="hidden" name="next" value="incident"/>
                {% endif %}
                <input type="submit" class="btn btn-small" name="cancel" value="Cancel" />
                <input type="submit" class="btn btn-danger " value="Confirm" />
            </span>
        </form>
    </div>
</div>

{% endblock content %}

ils/notifications_nsir/templates/notifications_nsir/subscription_create.html
{% extends BASE_TEMPLATE %}

{% block title %}Unsubscribe{% endblock title %}

{% block page_title %}<h3>Unsubscribe</h3>{% endblock page_title %}

{% block extra_css %}
{% endblock extra_css %}

{% block extra_js %}
{% endblock %}

{% block content %}

<div class="row">
    <div class="span5">
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to unsubscribe from Incident #{{object.incident.incident_id}}?</p>
            <span class="pull-right">
                <input type="submit" class="btn btn-small" name="cancel" value="Cancel" />
                <input type="submit" class="btn btn-danger " value="Confirm" />
            </span>
        </form>
    </div>
</div>

{% endblock content %}