ils/ils/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import RedirectView
from django.contrib import admin
from django.conf import settings
# from incidents_nsir.forms import CustomPasswordResetForm
admin.autodiscover()

urlpatterns = patterns('',
    # url('^', include('django.contrib.auth.urls')),
    url(r'^$', RedirectView.as_view(url=reverse_lazy(settings.DEFAULT_TAXONOMY + ":report")),name="home"),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^password_reset/$', 'incidents_nsir.reset_views.password_reset', name="password_reset"),
    # url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
    # url(r'^logout$', 'django.contrib.auth.views.logout',{'next_page':reverse_lazy("login")}, name="logout"),
    url(r'^nsir/', include('incidents_nsir.urls', namespace="incidents_nsir", app_name="incidents_nsir")),
    url(r'^notifications_nsir/', include('notifications_nsir.urls', namespace="notifications_nsir", app_name="notifications_nsir")),
    url(r'^comments/', include('fluent_comments.urls')),

    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout',{'next_page':reverse_lazy("login")}, name="logout"),
    url(r'^password_change/$', 'incidents_nsir.reset_views.password_change', name='password_change'),
    url(r'^password_change/done/$', 'incidents_nsir.reset_views.password_change_done', name='password_change_done'),
    url(r'^password_reset/$', 'incidents_nsir.reset_views.password_reset', name='password_reset'),
    url(r'^password_reset/done/$', 'incidents_nsir.reset_views.password_reset_done', name='password_reset_done'),
    # Support old style base36 password reset links; remove in Django 1.7
    url(r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'incidents_nsir.reset_views.password_reset_confirm_uidb36'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'incidents_nsir.reset_views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^reset/done/$', 'incidents_nsir.reset_views.password_reset_complete', name='password_reset_complete'),
    # The following urlconf allows access to media files (images uploaded to incidents)
    url(r'^media/incidentimages/(?P<filename>.*)$', 'incidents_nsir.views.protected_media')
)

# This method only works for serving media files on dev server. The production server
# can serve as well, but need to restrict access to files (only if logged in)
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ils/incidents_nsir/urls.py
from django.conf.urls import patterns, include, url
import views

urlpatterns = patterns('',
    url(r'^report/$', views.IncidentReport.as_view(), name="report"),
    url(r'^dashboard/$', views.Dashboard.as_view(), name="dashboard"),
    # url(r'^news/$', views.News.as_view(), name="news"),
    url(r'^incident/(?P<incident_id>\d+)/$', views.IncidentInvestigation.as_view(), name="incident"),

    url(r'^search/$',views.Search.as_view(), name="search"),
    url(r'^incident-summary/(?P<incident_id>\d+)/$', views.IncidentSummary.as_view(), name="incident-summary"),

    url(r'^change-event-type/(?P<incident_id>\d+)/$', views.ChangeEventType.as_view(), name="change-event-type"),

    # Investigation Lists
    url(r'^triage/$', views.TriageIncidentsList.as_view(), name="triage-incidents"),
    url(r'^incomplete-incidents/$', views.IncompleteIncidentsList.as_view(), name="incomplete-incidents"),
    url(r'^flagged-incidents/$', views.IncompleteAndFlaggedIncidentsList.as_view(), name="flagged-incidents"),
    url(r'^all-flagged-incidents/$', views.FlaggedIncidentsList.as_view(), name="all-flagged-incidents"),
    url(r'^complete-incidents/$', views.CompleteIncidentsList.as_view(), name="complete-incidents"),
    url(r'^actual-incidents/$', views.ActualIncidentsList.as_view(), name="actual-incidents"),
    url(r'^invalid-incidents/$', views.InvalidIncidentsList.as_view(), name="invalid-incidents"),
    url(r'^all-incidents/$', views.AllIncidentsList.as_view(), name="all-incidents"),
    # User Investigation lists
    url(r'^my-incidents/$', views.MyIncidentsList.as_view(), name="my-incidents"),
    url(r'^my-investigations/$', views.MyInvestigationsList.as_view(), name="my-investigations"),
    url(r'^my-patients/$', views.MyPatientsList.as_view(), name="my-patients"),

    # Action Lists
    url(r'^incomplete-actions/$', views.IncompleteActionsList.as_view(), name="incomplete-actions"),
    url(r'^complete-actions/$', views.CompleteActionsList.as_view(), name="complete-actions"),
    url(r'^all-actions/$', views.AllActionsList.as_view(), name="all-actions"),
    # User Action lists
    url(r'^my-assigned-by-actions/$', views.AssignedByActionsList.as_view(), name="my-assigned-by-actions"),
    url(r'^my-responsible-actions/$', views.ResponsibleActionsList.as_view(), name="my-responsible-actions"),
    url(r'^my-completed-actions/$', views.MyCompleteActionsList.as_view(), name="my-completed-actions"),

    # Sharing Lists
    url(r'^incomplete-sharing/$', views.IncidentReport.as_view(), name="incomplete-sharing"),
    url(r'^complete-sharing/$', views.IncidentReport.as_view(), name="complete-sharing"),
    url(r'^all-sharing/$', views.IncidentReport.as_view(), name="all-sharing"),
    # User Share lists
    url(r'^my-incomplete-sharing/$', views.IncidentReport.as_view(), name="my-incomplete-sharing"),
    url(r'^my-complete-sharing/$', views.IncidentReport.as_view(), name="my-complete-sharing"),
    url(r'^my-sharing/$', views.IncidentReport.as_view(), name="my-sharing"),

    # Statistics
    url(r'^statistics/$', views.Statistics.as_view(), name="statistics"),
    url(r'^incomplete-statistics/$', views.IncidentReport.as_view(), name="incomplete-statistics"),

    url(r'^reload_fk_choices.html$', views.reload_fk_choices_view, name="reload_fk_choices"),
    url(r'^reload_user_choices.html$', views.reload_user_choices_view, name="reload_user_choices"),
    url(r'^get_field_values.html$', views.get_field_values_view, name="get_field_values"),
    url(r'^save_new_template.html$', views.save_new_template_view, name="save_new_template"),
    url(r'^save_new_image.html$', views.save_new_image_view, name="save_new_image"),

    # AJAX urls
    # url(r'^ajax/$', views.ajax_view, name='ajax'),
)

ils/incidents_nsir/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist, FieldError, ValidationError
from django.core import serializers
from django.core.serializers.json import DjangoJSONEncoder
from django.core.servers.basehttp import FileWrapper
from django.core.urlresolvers import reverse
from django.db.models import Q, Max, FieldDoesNotExist
from django.db.models.loading import get_model
from django.forms.models import model_to_dict
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.template import Context, RequestContext
from django.template.loader import get_template
from django.utils import formats, timezone
from django.utils.translation import ugettext as _
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, DetailView, TemplateView, FormView

from listable.views import BaseListableView, SELECT
from listable.views import Column as C

import operator
import os
import json
import collections
import datetime
import time
import re
from time import strftime

import forms
import models
import feeds
import statistics
from notifications_nsir import signals
from accounts.models import ILSUser

import subprocess

#-----------------------------------------------------------------------------------------
# View constants:
# BASE_TEMPLATE - base template to inherit from
# USER - current SaILS user
# MONTHS - array of months used for formatting purposes (Dashboard view)
# MIN/MAX_ONLINE_ID - identify the range of ID numbers set aside for online reports
#-----------------------------------------------------------------------------------------
BASE_TEMPLATE = "incidents_nsir/base_nsir.html"
User = get_user_model()
MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
MIN_ONLINE_ID = 100000
MAX_ONLINE_ID = 200000

#-----------------------------------------------------------------------------------------
# Abstract Views & Mixins
#-----------------------------------------------------------------------------------------
class StaffRequiredMixin(object):
    """Raise authorization error if user is anonymous (not logged in).

    Parent class (not standalone) which provides condition on the dispatch() method; only
    allow processing of the desired GET/POST if the user has appropriate change_incident
    permissions. Note overrides the default dispatch() method for object class.
    """
    def dispatch(self, request, *args, **kwargs):
        #if not request.user.is_superuser:
        if self.request.user.is_anonymous():
            raise PermissionDenied("You don't have authorization to view this page")
        return super(StaffRequiredMixin, self).dispatch(request, *args, **kwargs)

class RequestUserFormMixin(object):
    """Add currently logged in user to kwargs of the current view.

    Parent class (not standalone) which modifies the get_form_kwargs() method.
    get_form_kwargs returns a dictionary of kwargs that will be passed to __init__ of a
    form. The modification provided here adds a new "user" entry to kwargs, which is the
    user submitting the HTTP request object. Example usage: to autofill the submitted_by
    field on the initial report page.
    """
    def get_form_kwargs(self):
        kwargs = super(RequestUserFormMixin, self).get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

class LoginRequiredMixin(object):
    """Require user to be logged in to access page governed by a view which inherits from
    this mixin.

    If the current user accessing a LoginRequiredMixin page is not logged in, they will
    be redirected to a login page (which after successful login, will redirect the user
    to the originally intended destination).
    """
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view)

class NewPasswordMixin(object):
    """Require user to have changed their password before visiting the current page.

    Intercepts the current view request. If the user who created the request is logged in
    and must change their password, then they will be redirected to the password reset
    page when trying to access any view which inherits from this mixin.
    """
    def dispatch(self, request, *args, **kwargs):
        #if not request.user.is_superuser:
        if not self.request.user.is_anonymous() and self.request.user.must_change_password:
            return HttpResponseRedirect(reverse("password_change"))
        return super(NewPasswordMixin, self).dispatch(request, *args, **kwargs)

@login_required
def protected_media(request, filename):
    """View used to serve restricted media files (images uploaded to incidents)- 
    require users to be logged in to access media files.
    """
    wrapper = FileWrapper(file(settings.RESTRICTED_MEDIA_URL+filename))
    response = HttpResponse(wrapper, content_type='text/plain')
    response['Content-Length'] = os.path.getsize(settings.RESTRICTED_MEDIA_URL+filename)
    return response

#-----------------------------------------------------------------------------------------
# Non-Abstract Views
#-----------------------------------------------------------------------------------------
class IncidentReport(RequestUserFormMixin,NewPasswordMixin, CreateView):
    """View used to handle submission of initial event reports.
    """
    model = models.Incident
    form_class = forms.IncidentReportForm
    template_name = "incidents_nsir/incident_report_nsir.html"

    def get_initial(self):
        """Determine which form values should be initialized.

        Based on the role of the current user, initialize form values for the investigator
        and type of report (online vs. paper) accordingly.

        Returns:
            A dictionary whose keys are incident form fields and whose values depend on
            the user accessing the page.
        """
        initial = super(IncidentReport, self).get_initial()
        if self.request.user.is_anonymous():
            if settings.INVESTIGATOR_ANONYMOUS:
                initial["investigator"] = ILSUser.objects.get(username=settings.INVESTIGATOR_ANONYMOUS)
            initial["report_type"] = models.ReportType.objects.get(pk=2)
            return initial
        else:
            try:
                current_role=self.request.user.role.name
                if settings.INVESTIGATOR_ADMIN and current_role == "admin":
                    initial['investigator'] = ILSUser.objects.get(username=settings.INVESTIGATOR_ADMIN)
                elif settings.INVESTIGATOR_THERAPY and current_role == "therapist":
                    initial['investigator'] = ILSUser.objects.get(username=settings.INVESTIGATOR_THERAPY)
                elif settings.INVESTIGATOR_DOSIMETRY and current_role == "dosimetrist":
                    initial['investigator'] = ILSUser.objects.get(username=settings.INVESTIGATOR_DOSIMETRY)
                elif settings.INVESTIGATOR_PHYSICS and current_role == "physicist":
                    initial['investigator'] = ILSUser.objects.get(username=settings.INVESTIGATOR_PHYSICS)
                elif settings.INVESTIGATOR_ONCOLOGY and current_role == "physician":
                    initial['investigator'] = ILSUser.objects.get(username=settings.INVESTIGATOR_ONCOLOGY)

                if current_role == "admin" or current_role == "dosimetrist" or current_role == "physicist" or current_role == "physician":
                    initial['report_type'] = models.ReportType.objects.get(pk=2)
                else:
                    initial['report_type'] = models.ReportType.objects.get(pk=1)

                return initial
            except AttributeError:
                return initial

    def post(self, request, *args, **kwargs):
        """Explicitly include post method in case need to add future functionality.
        """
        return super(IncidentReport, self).post(self,request)

    def render_to_json_response(self,context,**response_kwargs):
        """Function which renders the report page when the request is an ajax request.

        Render the report page (template) via an ajax request. Such a request is made upon
        attempting to submit an incident report. 

        Args:
            response_kwargs: dictionary containing keys 'changed', 'incident_id', and
            'errors'. These indicate which fields changed, the unique ID, and any errors
            respectively.

        Returns:
            Returns an HttpResponse object to load the current page, while maintaining all
            currently filled fields and highlighting any errors in red. The object will 
            also indicate which fields were just changed since the previous page rendering
            and the current incident ID. 
        """
        data = json.dumps(context)
        response_kwargs['content_type'] = 'application/json'
        return HttpResponse(data, **response_kwargs)

    def form_valid(self, form):
        """When valid form data has been POSTed: save the model instance and return an 
        HttpResponse.

        Overriding the parent method to allow for setting of additional model instance 
        field values, sending of email signals, and processing request as ajax.

        Args:
            form: Accept the current (filled) incident report form.

        Returns:
            An HttpResponse object that redirects user to the same page. If the request is
            ajax, return current filled in form. If the request is not ajax, return a
            fresh (empty) report page. Current implementation uses ajax requests.
        """
        self.get_form

ils/incidents_nsir/templates/incidents_nsir/base_nsir.html
{% extends 'base.html' %}
{%comment%}
  Base NSIR template from which all other NSIR templates within SaILS inherit. This template fills in the blocks from base.html for the various nav-bar buttons.
{%endcomment%}
{% load staticfiles %}

{% block report %}
  <li><a href="{% url 'incidents_nsir:report' %}"><i class="icon-bullhorn"></i> Report An Incident</a></li>
{% endblock report %}

{% block dashboard %}
  <li><a href="{% url 'incidents_nsir:dashboard' %}" title="View Incident Dashboard"><i class="icon-dashboard"></i> Dashboard</a></li>
{% endblock dashboard %}

{% block news %}
  <li><a href="{% url 'incidents_nsir:news' %}" title="View News Items"><i class="icon-inbox"></i> News</a></li>
{% endblock news %}

{% block search %}
  
  <li><a href="{% url 'incidents_nsir:search' %}" title="Search for an incident"><i class="icon-search"></i> Search</a></li>

  {%comment%}
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
       <i class="icon-search"></i> Search <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
        <div class="input-append">
          <input class="span2" id="appendedInputButton" type="text" placeholder="Unique Incident ID">
          <button class="btn" type="submit">Search <i class="icon-search"></i></button>
        </div>
      </li>
    </ul>
  </li>
  {%endcomment%}
{% endblock search %}

{% block incidents %}
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <i class="icon-exclamation-sign"></i> Incidents <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li class="nav-header">Incidents</li>
      {#<li><a href="{% url 'incidents_nsir:triage-incidents' %}" title="Triage recently reported incidents"><i class="icon-archive"></i> Awaiting Triage</a></li>#}
      <li><a href="{% url 'incidents_nsir:incomplete-incidents' %}" title="View incomplete incidents"><i class="icon-folder-open"></i> Incomplete</a></li>
      {#<li><a href="{% url 'incidents_nsir:flagged-incidents' %}" title="View incomplete and flagged incidents"><i class="icon-flag"></i> Incomplete & Flagged</a></li>#}
      <li><a href="{% url 'incidents_nsir:complete-incidents' %}" title="View all completed incidents"><i class="icon-folder-close"></i> Complete</a></li>
      <li><a href="{% url 'incidents_nsir:all-flagged-incidents' %}" title="View all flagged incidents"><i class="icon-flag"></i> Flagged</a></li>
      {#<li><a href="{% url 'incidents_nsir:actual-incidents' %}" title="View all valid actual incidents"><i class="icon-warning-sign"></i> Actual</a></li>#}
      <li><a href="{% url 'incidents_nsir:invalid-incidents' %}" title="View all invalid incidents"><i class="icon-ban-circle"></i> Invalid</a></li>
      <li><a href="{% url 'incidents_nsir:all-incidents' %}" title="View all incidents"><i class="icon-globe"></i> All Incidents</a></li>

      <li class="divider"></li>
      <li class="nav-header">Your Incidents</li>
      {%if user.is_oncologist%}
      <li><a href="{% url 'incidents_nsir:my-patients' %}" title="View all incidents involving your patients"><i class="icon-stethoscope"></i> Involving Your Patients</a></li>
      {%endif%}
      <li><a href="{% url 'incidents_nsir:my-incidents' %}" title="View all incidents you have submitted"><i class="icon-user"></i> Submitted By You</a></li>
      <li><a href="{% url 'incidents_nsir:my-investigations' %}" title="View all incident investigations you have been assigned "><i class="icon-zoom-in"></i> Your Investigations</a></li>
    </ul>
  </li>
{% endblock incidents %}

{% block actions %}
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <i class="icon-wrench"></i> Actions <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li class="nav-header">Actions</li>
      <li><a href="{% url 'incidents_nsir:incomplete-actions' %}" title="View incomplete learning actions"><i class="icon-folder-open"></i> Incomplete</a></li>
      <li><a href="{% url 'incidents_nsir:complete-actions' %}" title="View all completed actions"><i class="icon-folder-close"></i> Complete</a></li>
      <li><a href="{% url 'incidents_nsir:all-actions' %}" title="View all actions"><i class="icon-globe"></i> All Actions</a></li>
      <li class="divider"></li>
      <li class="nav-header">Your Actions</li>
      <li><a href="{% url 'incidents_nsir:my-assigned-by-actions' %}" title="View all incomplete actions you have been assigned "><i class="icon-share-alt"></i> Assigned By You</a></li>
      <li><a href="{% url 'incidents_nsir:my-responsible-actions' %}" title="View all complete actions you have been assigned "><i class="icon-reply"></i> Assigned To You</a></li>
      <li><a href="{% url 'incidents_nsir:my-completed-actions' %}" title="View all complete actions you have been assigned "><i class="icon-ok-sign"></i> Completed By You</a></li>
    </ul>
  </li>
{% endblock actions %}

{% block sharing %}
  <ul class="dropdown-menu">
    <li class="nav-header">Sharing</li>
    <li><a href="{% url 'incidents_nsir:incomplete-sharing' %}" title="View incomplete sharing"><i class="icon-folder-open-alt"></i> Incomplete</a></li>
    <li><a href="{% url 'incidents_nsir:complete-sharing' %}" title="View all completed sharing"><i class="icon-folder-close-alt"></i> Complete</a></li>
    <li><a href="{% url 'incidents_nsir:all-sharing' %}" title="View all sharing"><i class="icon-globe"></i> All Sharing</a></li>

    <li class="divider"></li>
    <li class="nav-header">My Sharing</li>
    <li><a href="{% url 'incidents_nsir:my-incomplete-sharing' %}" title="View all incomplete sharing you have been assigned "><i class="icon-zoom-in"></i> Incomplete</a></li>
    <li><a href="{% url 'incidents_nsir:my-complete-sharing' %}" title="View all complete sharing you have been assigned "><i class="icon-zoom-in"></i> Complete</a></li>
    <li><a href="{% url 'incidents_nsir:my-sharing' %}" title="View all incident investigations you have been assigned "><i class="icon-zoom-in"></i> All</a></li>
  </ul>
{% endblock sharing %}

{% block statistics %}
  <li><a href="{% url 'incidents_nsir:statistics' %}"><i class="icon-bar-chart"></i> Statistics</a></li>
{% endblock statistics %}

{%comment%}
{% block statistics %}
  <ul class="dropdown-menu">
    <li><a href="{% url 'incidents_nsir:statistics' %}" title="View overall statistics"><i class="icon-bar-chart"></i> Overall</a></li>
    {% if perms.incidents %}
    <li><a href="{% url 'incidents_nsir:incomplete-statistics' %}" title="View statistics on incomplete incidents"><i class="icon-folder-open-alt"></i> Incomplete</a></li>
    {% endif %}
  </ul>
{% endblock statistics %}
{%endcomment%}

{% block nav_login_redirect %}
  <input type="hidden" name="next" value="{% url 'incidents_nsir:dashboard' %}"/>
{% endblock nav_login_redirect %}

ils/incidents_nsir/templates/incidents_nsir/change_event_type.html
{% extends BASE_TEMPLATE %}
{%comment%}
  Webpage used to change the event type of an incident following an initial report
{%endcomment%}
{% load staticfiles %}
{% load custom_tags %}

{% block title %}Change Event Type: Incident #{{ incident.incident_id}}{% endblock title %}
{% block page_title %}<h3>Change Event Type: Incident #{{ incident.incident_id}}</h3>{% endblock page_title%}

{% block extra_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'chosen/chosen.css'%}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'incidents_nsir/css/change_event_type.css'%}"/>
{% endblock extra_css %}

{% block extra_js %}
  <script src="{% static 'chosen/chosen.jquery.js' %}"></script>
  <script src="{% static 'incidents_nsir/js/change_event_type.js' %}"></script>
  <script type="text/javascript">
    var thisInc = {{ incident.incident_id }};
  </script>
{% endblock extra_js %}

{%block content%}
<div>
  <div class="row">
    <div class="span12">
      <div class="row">
        <div class="span7" id="instructions">
          <p>
            Please change the Event Type and associated fields as required. 
          </p>
          <p>
            Click the blue Update button to save changes.
          </p>
          <p>
            Note that if the Event Type is changed, some additional fields may now be mandatory on the Investigation Form.
          </p>
          <hr>
        </div>
      </div>
    </div>
  </div>
</div>
<div id="form-div">
  <div class="row">
    <div class="span12">
      <div class="row">
        <div class="span7">
          <form autocomplete="off" id="change-event-type-form" class="form-horizontal" method="post">
            <input type="hidden" name="form_name" value="change_event_type_form" />
            <input type="hidden" name="next" value="incident"/>
            {% csrf_token %}
            {# Note the use of custom template tags here to format tooltips as desired #}
            {% for field in form %}
              {% is_foreignkey field %}
              {% get_label_key field.auto_id %}
              <div class="control-group ils-popover {% if field.errors %}error{% endif %}"
                id="hide-{{ label_key }}"
                {% if field.label == form.event_type.label %}
                data-original-title="<strong>{{field.label}}</strong>"
                {#data-content="{{field.help_text}}"#}
                data-content="
                {% get_help_text help_dictionary label_key %}
                {% for inst in myinstances %}
                  <b>{{inst.name|linebreaks}}</b>
                  {{inst.description|linebreaks}}
                {% endfor %}
                "
                {% elif field.label == form.oncologist.label %}
                data-original-title="<strong>{{form.oncologist.label}}</strong><br>{{form.oncologist.help_text}}"
                data-content="                  
                    Please note, an email will be sent to notify the physician if different than before.
                "
                {% else %}
                data-original-title="<strong>{{field.label}}</strong>"
                data-content="{{field.help_text}}"
                {% endif %}
                >

                {# The following adds an asterisk to required field labels #}
                <label class="control-label" for="{{field.html_name}}">{{field.label}}{#{% if field.field.required %}*{% endif %}#}</label>

                <div class="controls" >
                  {{field}}
                  {% for error in field.errors %}
                    <span class="help-block">{{error}}</span>
                  {% endfor %}
                </div>
              </div>
            {%endfor%}
            <button type="submit" class="btn btn-primary update-event-type my-shader" style="float: right;">Update</button>
            <button type="button" class="btn btn-primary cancel-change cancel-shader" style="float: left;" onclick="location.href='{%url 'incidents_nsir:incident' incident_id=incident.incident_id %}#impact'">Cancel Change</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{%endblock content%}

ils/incidents_nsir/templates/incidents_nsir/dashboard_nsir.html
{% extends 'dashboard.html' %}
{% load staticfiles %}

{% block taxonomy_js %}
  <script src="{% static 'incidents_nsir/js/dashboard.js' %}"></script>
{% endblock taxonomy_js %}

ils/incidents_nsir/templates/incidents_nsir/incident_report_nsir.html
{% extends 'incident_report.html' %}
{% load staticfiles %}

{% block taxonomy_js %}
  <script src="{% static 'incidents_nsir/js/report.js' %}"></script>
{% endblock taxonomy_js %}

ils/incidents_nsir/templates/incidents_nsir/list_nsir.html
{% extends 'base.html' %}

{% load static %}
{% load listable %}

{% block extra_css %}
    {% listable_css %}
{% endblock extra_css %}

{% block extra_js %}
    <script src="{% static 'incidents_nsir/js/list_nsir.js' %}"></script>
    {% listable 'incidents_nsir:triage' save_state=True css_input_class="input-xs " %}
{% endblock extra_js %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        {{listable_table}}
    </div>
</div>
{% endblock content %}